[package]
name = "forge"
version = "0.1.0"
authors = ["Gregory Mitrano <gregory.mitrano@gmail.com>"]
edition = "2018"

[dependencies]
failure = "0.1.3"
ws = "0.7.9"

[profile.release]
panic = "abort"

[lib]
name = "forge"
crate-type = ["lib", "cdylib"]

[build-dependencies]
cbindgen = "0.6.7"